Repository SymmetrySyndicate/jangal, pull requests merged in 2025-04, with the labels that each got.

#2 feat(c): add Van Emde Boas trees implementation in C
  .github/workflows/c-tests.yml
  .gitignore
  .pre-commit-config.yaml
  src/c/Makefile
  src/c/example.c
  src/c/include/vEB.h
  src/c/src/vEB.c
  src/c/tests/test_vEB.c
Labels: feature :rocket:, c

#3 chore(dev): add script to generate clangd cfg
  .github/dev/generate_clangd_cfg.sh
  .gitignore
Labels: documentation :book:

#7 feat(python/tree): add a `Tree` base class
  src/python/pyproject.toml
  src/python/src/trees/base.py
  src/python/src/trees/veb.py
Labels: feature :rocket:, python :snake:
